// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHub.Infrastructure;

namespace SmartHub.Domain.Migrations
{
    [DbContext(typeof(SmartHubContext))]
    partial class SmartHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SmartHub.Infrastructure.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnName("description");

                    b.Property<Guid>("DeviceId")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<Guid?>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasAlternateKey("DeviceId")
                        .HasName("ak_devices_device_id");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("SmartHub.Infrastructure.Entities.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("DtSend")
                        .HasColumnName("dt_send");

                    b.Property<int>("Type")
                        .HasColumnName("type");

                    b.Property<double>("Value")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_measurements");

                    b.ToTable("measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
